Exam/website/bboard/urls.py
from django.contrib import admin
from django.urls import path, include
from bboard.views import *
from users.views import *

urlpatterns = [
    path('', index),
    # path('students/', students, name="students"),
]

Exam/website/users/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import *
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('login/', login_view, name="login"),
    path('auth/', auth_view, name="auth"),
    path('logout/', logout_view, name="logout"),
    path('grappelli/', include('grappelli.urls')),
    path('active-profiles/', NotBannedProfilesList.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Exam/website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from bboard.views import *
from users.views import *
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('', index, name='index'),
    path('students/', students, name="students"),
    path('user/', include('users.urls')),
    path('bboard/', include('bboard.urls')),
    path('admin/', admin.site.urls),
    path('post/<int:post_id>/', posts_detail, name='posts_detail'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('create/', create, name="create"),
    path('comments/', comments, name="comments"),
    path('posts/', posts, name="posts"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Exam/website/bboard/models.py
from django.db import models
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views import generic

class Post(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=250, verbose_name='Загаловок')
    text = models.TextField(verbose_name='Текст')
    published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')
    img = models.ImageField(upload_to='product', null=True, blank=True, verbose_name='Изображение', default='default.jpg')

class Comment(models.Model):
    id = models.BigAutoField(primary_key=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(max_length='100', verbose_name='Комментарии')

Exam/website/users/models.py
from django.db import models
from django.core import validators
from django.contrib.auth.models import User

class Profile(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, default='+79999999999')
    is_banned = models.BooleanField(default=False)
    img = models.ImageField(upload_to='product', null=True, blank=True, verbose_name='Аватар', default='ava.png')

Exam/website/bboard/forms.py
from django.forms import ModelForm
from bboard.models import Comment, Post
from django.contrib.auth.models import User

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('img', 'title', 'text')

Exam/website/bboard/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader
from bboard.models import *
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.views.generic.edit import CreateView
from django.views.generic import DetailView, ListView
from bboard.forms import CommentForm, PostForm
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def index(request):
    template = loader.get_template('main/index.html')
    pub = Post.objects.order_by('published')
    context = {'pub':pub}
    return HttpResponse(template.render(context, request))

def students(request):
    template = loader.get_template('main/students.html')
    context = {}
    return HttpResponse(template.render(context, request))

def create(request):
    template = loader.get_template('main/create.html')
    context = {}
    return HttpResponse(template.render(context, request))

def main(request):
    template = loader.get_template('main/index.html')
    usr = Post.objects.order_by('user')
    context = {'usr': usr}
    return HttpResponse(template.render(context, request))

def posts_detail(request, post_id):
    template = loader.get_template('main/posts.html')
    post = get_object_or_404(Post, id=post_id)
    comments = Comment.objects.filter(post_id=post_id).order_by('-id')
    form = CommentForm()
    form_post = PostForm()
    context = {'post':post, 'comments':comments, 'form': form, 'form_post':form_post}
    return HttpResponse(template.render(context, request))

def posts(request):
    if request.method == 'POST':
        user_id = request.user.id
        title = request.POST.get('title')
        text = request.POST.get('text')
        post = Post(user_id=user_id, title=title, text=text)
        post.save()
        paginator = Paginator(post, 3)
        page = request.GET.get('page')
        try:
            postes = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer deliver the first page
            postes = paginator.page(1)
        except EmptyPage:
            # If page is out of range deliver last page of results
            postes = paginator.page(paginator.num_pages)
        return render(request, 'main/index.html', {'page': page, 'postes': postes})
        # return redirect('index')

def comments(request):
    if request.method == 'POST':
        user_id = request.user.id
        post_id = request.POST.get('post_id')
        text = request.POST.get('text')
        comment = Comment(user_id=user_id, post_id=post_id, text=text)
        comment.save()
        return redirect('posts_detail', post_id=post_id)

Exam/website/users/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.template import loader
from .models import *
from users.models import Profile
from django.http import Http404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework import serializers
from bboard.templatetags.custom_tags import censor
from django.shortcuts import redirect

def login_view(request):
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)


        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            return HttpResponse('Login error')
    else:
        return render(request, 'users/login.html', {})

def auth_view(request):
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
            if user is not None:
                return HttpResponse('Такой пользователь существует!')
        except User.DoesNotExist:
            User.objects.create_user(username, password=password)
            return render(request, 'users/login.html', {})


    else:
        return render(request, 'users/auth.html', {})

def logout_view(request):
    logout(request)
    return redirect('index')


class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = '__all__'



class ProfileSerializer(serializers.ModelSerializer):
    user = UserSerializer()

    class Meta:
        model = Profile
        fields = '__all__'

class NotBannedProfilesList(APIView):
    def get(self, request, format=None):
        profiles = Profile.objects.filter(is_banned=False)
        serializer = ProfileSerializer(profiles, many=True)
        return Response(serializer.data)

def profile(request):
    user_id = request.user.id
    template = loader.get_template('main/index.html')
    profile = Profile.objects.get(user_id=user_id)
    context = {'profile': profile}
    return HttpResponse(template.render(context, request))

Exam/website/users/templates/layouts/main.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<link rel="stylesheet" href="{% static 'style/main.css' %}">
<script type="text/javascript" src="http://code.jquery.com/jquery-1.11.1.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.12.0/jquery.validate.js"></script>
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.12.0/additional-methods.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="{% static 'script/main.js' %}"></script>

<head>
    <meta charset="UTF-8">
    <title>ITStep: Форма</title>
</head>
<body>
<div id='page'>
    <div id="slip-menu">
        <span>
            <img style="width: 50px" src="/media/logo.png">
            <div id='logo-text'>
                <h1>STEP</h1><br>
                <p>IT ACADEMY</p>
            </div>
        </span>
        <ul>
            <li style="color: #96a8ff">ITSTEP</li>
            <li><a href="{% url 'index' %}">Главная</a></li>
            <li><a href="{% url 'students' %}">Ученики</a></li>
            <li>Достижения</li>
            <li>Форма</li>
            <li>Контакты</li>
        </ul>
        <div id="admin-button-sticky" style="color: white">
            {% if user.is_authenticated %}
                        {{ user }}
            {% else %}
                <p><a href="{% url 'login' %}">ВОЙТИ</a></p>
            {% endif %}
        </div>
    </div>
    <menu>
        <ul>
            <li style="color: #96a8ff">ITSTEP</li>
            <li><a href="{% url 'index' %}">Главная</a></li>
            <li><a href="{% url 'students' %}">Ученики</a></li>
            <li>Достижения</li>
            <li>Форма</li>
            <li>Контакты</li>
        </ul>
    </menu>
    <div id="logo">
        <span>
            <img style="width: 50px" src="/media/logo.jpeg">
            <div id='logo-text'>
                <h1>STEP</h1><br>
                <p>IT ACADEMY</p>
            </div>
        </span>
        <div id="search">
            <input type="text" placeholder="поиск по сайту">
            <img src="https://cdn2.iconfinder.com/data/icons/user-interface-169/32/search-256.png">
        </div>
        <div id="admin-button">
            {% if user.is_authenticated %}
                <div id="login-plus">
                    {% for pro in prof %}
                        <img src="{{ pro.img }}">
                    {% endfor %}
                        {{ user }}
                </div>
            {% else %}
                <p><a href="{% url 'login' %}">ВОЙТИ</a></p>
            {% endif %}
        </div>
        <div id="user-menu">
            <p>Мой аккаунт</p>
            <p>Мои задания</p>
            <p>Настройки</p>
            <a href="{% url 'logout' %}" style="color: black"><p>Выйти</p></a>
        </div>
    </div>
    <main id='main'>

        {% block content %}
        {% endblock %}

    </main>
    <footer>
        <div id='footer'>
            <div id='col-1'>
                <p>Позвоните нам по телефону:</p>
                <p>8 (7172) 77-77-77</p>
            </div>
            <div id='col-2'>

            </div>
            <div id='col-3'>
                <img style="width: 50px; filter: invert(1);" src="https://cdn4.iconfinder.com/data/icons/doodle-4/158/send-256.png"><br>
                <a href="/admin">ADMIN PANEL</a><br>
                <a href="/api/token/">TOKEN</a><br>
                <a href="/user/active-profiles/">ACTIVE PROFILES</a>
            </div>
        </div>
    </footer>
</div>
</body>
</html>

Exam/website/users/templates/layouts/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

Exam/website/users/templates/main/create.html
{% extends 'layouts/main.html' %}
{% block content %}
    {% load static %}
    <script src="{% static 'script/create.js' %}"></script>
    <link rel="stylesheet" href="{% static 'style/create.css' %}">
    <div>
        {% if user.is_authenticated %}
            <div class="create-box">
                <h3>Добавить публикацию</h3>
                <form id="form" method="POST" action="/posts/">
                    {% csrf_token %}
                    <p>Заголовок</p>
                    <input type="text" name="title" required id="id_title">
                    <p>Текст поста</p>
                    <textarea name="text" cols="40" rows="10" maxlength="100" required="" id="id_text"></textarea>
                    <input type="hidden" name="user_id" value="{{ user.id }}"><br>
                    <input type="submit" id="submit-button" value="ОПУБЛИКОВАТЬ">
                </form>
            </div>
        {% endif %}
    </div>
{% endblock %}

Exam/website/users/templates/main/index.html
{% extends 'layouts/main.html' %}
{% block content %}
    {% load static %}
    <script src="{% static 'script/index.js' %}"></script>
    <link rel="stylesheet" href="{% static 'style/index.css' %}">
    <div id="content">
        <section style="display: inline-grid">
            <div id='news' uk-grid="masonry: true">
                {% for pu in pub %}
                    <div id="pub-box">
                        <div id="img">
                            <a href="{% url 'posts_detail' pu.id %}"><img src="/media/{{ pu.img }}" /></a>
                        </div>
                        <div id="pub-title">
                                <a href="{% url 'posts_detail' pu.id %}">{{ pu.title }}</a>
                        </div>
                        <div id="pub-text">
                            {{ pu.text }}
                        </div>
                        <div id="pub-info">
                            <span style="text-align: left">{{ pu.user }}</span>
                            <span style="text-align: right">{{ pu.published }}</span>
                        </div>
                    </div>
                {% endfor %}
                <div id="pub-box" style="justify-items: center; align-content: center">
                        <span class="post-text">
                            {% if user.is_authenticated %}
                                <a href="/create"><span class="plus">&#10010;</span></a>
                                <p>СОЗДАТЬ ПОСТ</p>
                            {% else %}
                                <a href="user/login"><span class="plus">&#10010;</span></a>
                                <p>СОЗДАТЬ ПОСТ</p>
                            {% endif %}
                        </span>
                </div>
            </div>
            <div id="pagination">
                {% include "layouts/pagination.html" with page=postes %}
            </div>
        </section>
        <section id="right-menu">
            {% if user.is_authenticated %}
                <div id="profile-info">
                    <h3 style="margin-bottom: 10px">{{ user }}</h3>
                    <h5><span>Имя: </span>{{ user.first_name }}</h5>
                    <h5><span>Фамилия: </span>{{ user.last_name }}</h5>
                    <h5><span>E-mail: </span>{{ user.email }}</h5>
                    <h5><span>Дата регистрации: </span>{{ user.date_joined }}</h5>
                    {{ profile.id }}
                </div>
            {% else %}
                <div id="auth">
                    <h3>АВТОРИЗАЦИЯ</h3>
                    <h4>Введите ваши данные для входа в портал и использование всех привелегии</h4>
                    <form action="{% url 'login' %}" method="POST">
                        {% csrf_token %}
                        <input type="text" id="login-user" name="username" placeholder="Логин"><br>
                        <input type="password" id="login-user" name="password" placeholder="Пароль"><br>
                        <input type="submit" id="login-button" value="ВОЙТИ">
                    </form>
                </div>
            {% endif %}
            <div class="calendar-wrapper">
                <button id="btnPrev" type="button">Предыдущий</button>
                <button id="btnNext" type="button">Следующий</button>
                <div id="divCal"></div>
            </div>
        </section>
    </div>
{% endblock %}

Exam/website/users/templates/main/posts.html
{% extends 'layouts/main.html' %}
{% block content %}
    {% load static %}
    {% load custom_tags %}
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.11.1.js"></script>
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.12.0/jquery.validate.js"></script>
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.12.0/additional-methods.js"></script>
    <script src="{% static 'script/posts.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'style/posts.css' %}">
    <div style="text-align: center; margin-bottom: 50px">
        <div id="publish">
                <div id="pub-title">
                    {{ post.title }}
                </div>
                <div id="img">
                    <img src="/media/{{ post.img }}" />
                </div>
                <div id="pub-text">
                    {% censor post.text %}
                </div>
        </div>
        <div id="comment">
            <h3>Комментарии пользователей</h3>
            <span><input type="checkbox" id="censor-check">Показать цензуру</span>
            {% for com in comments %}
                <div class="com">
                    <span class="user">Пользователь: {{ com.user }}</span><br>
                    <span class="com-text" id="com-text-{{ com.id }}">{% censor com.text %}</span>
                </div>
                <span id="com-{{ com.id }}" style="visibility: hidden; position: absolute">{{ com.text }}</span>
                <span id="con-{{ com.id }}" style="visibility: hidden; position: absolute">{% censor com.text %}</span>
            {% endfor %}
        {% if user.is_authenticated %}
            <div class="com" style="text-align: center">
                <p style="text-align: left; margin-left: 20px">Добавить комментарии</p>
                <form id="form" method="POST" action="/comments/">
                    {% csrf_token %}
                    <textarea name="text" cols="40" rows="10" maxlength="100" required="" id="id_text"></textarea>
                    <input type="hidden" name="post_id" value="{{ post.id }}">
                    <input type="hidden" name="user_id" value="{{ user.id }}">
                    <input type="submit" id="submit-button" value="ОТПРАВИТЬ">
                </form>
            </div>
        {% endif %}
        </div>
    </div>
{% endblock %}

Exam/website/users/templates/main/students.html
{% extends 'layouts/main.html' %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'style/students.css' %}">

    <h1 id="form-text">Список студентов</h1>
    <div id="box">
        <table id="content">
            <tr>
                <th>Курс обучения</th>
                <th>Имя</th>
                <th>Имя</th>
                <th>Фамилия</th>
                <th>Год рождения</th>
                <th>Номер телефона</th>
                <th>Комментарии</th>
            </tr>
            {% for tx in txt %}
            <tr>
                <td>{{ tx.lesson }}</td>
                <td>{{ tx.pk }}</td>
                <td>{{ tx.name }}</td>
                <td>{{ tx.surname }}</td>
                <td>{{ tx.birthday }}</td>
                <td id="ph_num">{{ tx.number }}</td>
                <td>{{ tx.comment }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}